### ISSUE TITLE
No Services on iOS using test app

### ISSUE THREAD

**Issue by dwebb72** [jbagg/QtZeroConf#47] opened 2021-09-09 16:16 UTC
I am using QT 5.15.2, Xcode 12.5.1 and iOS 14.7.1 and I get no services in the test_app.  addService or removeService never fires.

**Comment by jbagg** [comment] 2021-09-09 17:25
Hi, another use has reported the same iOS 14 issues as well.  Currently I'm working from home because of covid-19, which I expect will be the case until I retire.  I do not have access to a new enough mac to run a new enough xcode.  I would suggest making a very simple c app that uses DNSServiceBrowse() and see if that works.  This will tell us if the issue is in QZeroConf or if apple has busted or deprecated DNSServiceBrowse() c api.

**Comment by jbagg** [comment] 2021-09-10 01:20
Hi, another use has reported the same iOS 14 issues as well.  Currently I'm working from home because of covid-19, which I expect will be the case until I retire.  I do not have access to a new enough mac to run a new enough xcode.  I would suggest making a very simple c app that uses DNSServiceBrowse() and see if that works.  This will tell us if the issue is in QZeroConf or if apple has busted or deprecated DNSServiceBrowse() c api.

**Comment by dwebb72** [comment] 2021-09-10 12:56
Thanks for your response. Unfortunately, I don't have the experience in C to create this app. I won't be able to spend the time to figure out how to do that. I am more than willing to test an app on my setup.

**Comment by mzanetti** [comment] 2021-09-11 07:53
Did you guys request the local network permission as well as list the browsed service types in the info.plist file. It works fine for me on iOS with this Info.plist:

https://github.com/nymea/nymea-app/blob/master/packaging/ios/Info.plist.in#L40

**Comment by dwebb72** [comment] 2021-09-13 18:53
> Did you guys request the local network permission as well as list the browsed service types in the info.plist file. It works fine for me on iOS with this Info.plist:
> 
> https://github.com/nymea/nymea-app/blob/master/packaging/ios/Info.plist.in#L40

I added that but the app doesn't ask for access so it doesn't change anything.

**Comment by mzanetti** [comment] 2021-09-14 08:14
There must be a mistake in your info.plist then. It should pop up the question as soon as you create the QZeroConf object.

**Comment by dwebb72** [comment] 2021-09-14 15:05
@mzanetti you are correct. I didn't add the bonjour service types. For anyone else that is having this issue the video below explains it well.
https://developer.apple.com/videos/play/wwdc2020/10110/

Thanks

**Comment by jbagg** [comment] 2021-09-14 15:14
I will close this then,

**Comment by jbagg** [comment] 2021-09-14 15:15
I plan to add the plist info to the readme.md as well.

**Closed as completed by jbagg** 2021-09-14 15:14 UTC
